# example_package2_ryandaydev
Testing the process of publishing to pypi

## Purpose
This is a project I'm only testing to see how Python packaging works

## Decisions
Here are some decisions I made:

1. Using setuptools for the build
2. Using unittest for testing